### ISSUE TITLE
This not Issue

### ISSUE THREAD

**Issue by Kozlov-V** [liudongmiao/curl-android#2]
It is cool!
Please tell me, how i may execute upload POST file
as:
```curl -F file=@MY_FILE http://my_host/upload```
And too, may it NDK working on Android 2.3.3?

**Comment by liudongmiao** [comment]
public static native boolean curl_setopt(int curl, int option, NameValuePair[] value);

For file, please use FileNameValuePair

**Comment by Kozlov-V** [comment]
Thank you!
