### ISSUE TITLE
Curl对象的线程安全

### ISSUE THREAD

**Issue by perlmonk** [liudongmiao/curl-android#3]
我有个疑问，c代码里有这样一行

```c
static callback_t *callback = NULL;
```

看起来像是把callback保存成全局的了。如果多线程调用读写，貌似会出问题，另外运行到cleanup的时候会不会无法保证状态。

```c
static void curl_cleanup(JNIEnv *env, jobject clazz, jint handle)
{
	CURL *curl = (CURL *)handle;
	if (NULL != curl) {
		curl_easy_cleanup(curl);
	}

	if (callback) {
		deleteref(readobject);
		deleteref(writeobject);
		deleteref(headerobject);
		deleteref(debugobject);
		deleteref(progressobject);
	}
}
```

**Comment by liudongmiao** [comment]
是的，当时写的时候，其实连什么是jni都不知道。

已经更新了，请帮忙查看下。

http://curl.haxx.se/libcurl/c/libcurl-tutorial.html#Multi-threading
虽然已经使用c-ares，应该是支持多线程的，但是我并没有认真测试。

**Comment by perlmonk** [comment]
更新好快！您这个版本的封装很不错，代码非常整齐。
我需要用的其实只是curl里很小的一部分功能，我准备尝试自己编译下curl的库，遇到问题也许还要向您请教 :)

**Comment by perlmonk** [comment]
刚刚重新调试，并发请求没问题了，谢谢。
